spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quote_db
    username: postgres
    password: rootroot
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
